# Generated by Django 4.2.3 on 2023-07-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
